### ISSUE TITLE
door stuck

### ISSUE THREAD

**Issue by iStealPrefixes** [Blank256/parasitemod#1]
The phantom, exterior like fish eggs interior like suicide wrist-red(rags?) I could exercise you, this could be your phys-ed cheat on your man homie AGHHH I tried to sneak through the door man! Can't make it, can't make it, the shit's stuck! Outta my way son! DOOR STUCK! DOOR STUCK! Please! I beg you! We're dead! You're a g-g-genuine dick sucker!

**Comment by Blank256** [comment]
should be fixed in version 6942013373601337

**Comment by iStealPrefixes** [comment]
Herllo its me again; I noticed in the lkatest version the bug can still be achieved through the use of a light saber instead of excalibur on level 69 of the monalisa painting depth.
Could this please be resolved.

danke

-einen duff person

**Comment by Blank256** [comment]
Thijs shouldnty happen on level 69 of the moanlies panting dept. I wil tryt get this fix as soon as posbbilel!
thank you for the ropert!!!!!!!

-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
